**##MAE**

In [4]:
import numpy as np

y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.30, 0.7, 1, 0, 0.5])


In [6]:
def mae(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs(yt-yp)
    print("Total erro: ", total_error)
    mae = total_error/len(y_predicted)
    print('MAE: ', mae)
    return mae

In [8]:
mae(y_predicted, y_true)

Total erro:  2.5
MAE:  0.5


0.5

In [15]:
# Numpy gives us more productivity
np.mean(np.abs(y_predicted-y_true))

0.5

**##Log Loss Function**

In [20]:
# log(0) is undefined and that will create problem for us
np.log([0])

C:\Users\User\AppData\Local\Temp\ipykernel_3616\4018569617.py:2: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [19]:
np.log(0.0000000000000001)

-36.841361487904734

In [23]:
epsilon = 1e-15
epsilon

1e-15

In [25]:
y_predicted

array([1, 1, 0, 0, 1])

In [24]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [27]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [29]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [31]:
-np.mean( y_true*np.log(y_predicted_new) + (1-y_true)*np.log((1-y_predicted_new)))

17.2696280766844

In [33]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log((1-y_predicted_new)))

In [34]:
log_loss(y_true, y_predicted)

17.2696280766844